version: '3'
services:
  web:
    build: .
    ports:
      - '8080:80'
    volumes:
      - '.:/var/www'
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel_docker
      - DB_USERNAME=site
      - DB_PASSWORD=password
    depends_on:
      - database
  php-myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '9000:80'
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database
  database:
    image: mysql:5.7.22
    ports:
      - '13306:3306'
    environment:
      - MYSQL_DATABASE=laravel_docker
      - MYSQL_USER=site
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - './data:/var/lib/mysql'
